// src/constants/Categories.js
// RULE: All `name` values use underscore_keys for i18n translation compatibility.
// This file is the SINGLE SOURCE OF TRUTH for category keys.
// Frontend Categories.ts must always mirror this file exactly.
// NEVER store display strings in the database — always store the raw underscore key.

// === SELLER CATEGORIES (PRODUCTS) ===
const SELLERS_CATEGORIES = [
  // ── ELECTRONICS ──────────────────────────────────────────────────────────
  {
    name: "Phones_Tablets",
    icon: "smartphone",
    subcategories: [
      "Smartphones",
      "Feature_Phones",
      "Refurbished_Phones",
      "Tablets",
      "SIM_Cards",
      "Phone_Cases",
      "Screen_Protectors",
      "Phone_Stands",
      "Earphones_Headphones",
      "Bluetooth_Earbuds",
      "Smart_Watches",
      "Smart_Speakers",
      "Wearable_Technology",
      "Chargers_Cables",
      "Power_Banks",
      "Phone_Accessories",
      "Other",
    ],
  },
  {
    name: "Laptops_Computers",
    icon: "monitor",
    subcategories: [
      "Laptops",
      "Desktops",
      "All_in_One_Computers",
      "Mini_PCs",
      "Gaming_Laptops",
      "Gaming_Desktops",
      "Monitors",
      "Keyboards_Mice",
      "Webcams",
      "Printers",
      "Scanners",
      "Fax_Machines",
      "Storage_Devices",
      "Networking_Equipment",
      "Software",
      "Computer_Accessories",
      "Other",
    ],
  },
  {
    name: "TV_Audio_Gaming",
    icon: "tv",
    subcategories: [
      "Televisions",
      "Streaming_Devices",
      "Set_Top_Box",
      "Blu_ray_Players",
      "Soundbars",
      "Home_Theater",
      "Speakers",
      "Headphones",
      "Projectors",
      "Gaming_Consoles",
      "Video_Games",
      "Gaming_Accessories",
      "VR_Headsets",
      "TV_Accessories",
      "Other",
    ],
  },
  {
    name: "Cameras_Optics",
    icon: "camera",
    subcategories: [
      "DSLR_Cameras",
      "Mirrorless_Cameras",
      "Action_Cameras",
      "Camcorders",
      "Drones",
      "Security_Cameras_CCTV",
      "Dashcams",
      "Camera_Lenses",
      "Lens_Filters",
      "Tripods_Monopods",
      "Gimbals_Stabilizers",
      "Camera_Bags",
      "Lighting_Equipment",
      "Backdrops_Green_Screens",
      "Camera_Monitors",
      "Binoculars_Monoculars",
      "Photography_Accessories",
      "Other",
    ],
  },

  // ── FASHION & BEAUTY ─────────────────────────────────────────────────────
  {
    name: "Womens_Fashion",
    icon: "user",
    subcategories: [
      "Dresses",
      "Tops_Blouses",
      "Sweaters_Cardigans",
      "Coats_Jackets",
      "Hoodies_Sweatshirts",
      "Skirts",
      "Trousers_Jeans",
      "Jumpsuits_Playsuits",
      "Shorts",
      "Leggings_Tights",
      "Lingerie_Underwear",
      "Sleepwear",
      "Swimwear",
      "Activewear",
      "Native_Ankara",
      "Hijabs",
      "Veils",
      "Abayas_Jilbabs",
      "Kimonos",
      "Shoes_Heels",
      "Sneakers_Flats",
      "Sandals_Slippers",
      "Handbags_Clutches",
      "Backpacks",
      "Jewelry",
      "Watches",
      "Belts_Scarves",
      "Sunglasses",
      "Hair_Accessories",
      "Other",
    ],
  },
  {
    name: "Mens_Fashion",
    icon: "user",
    subcategories: [
      "Shirts",
      "T_Shirts_Polos",
      "Hoodies_Sweatshirts",
      "Trousers_Chinos",
      "Jeans",
      "Shorts",
      "Suits_Blazers",
      "Native_Wear",
      "Underwear_Socks",
      "Sleepwear",
      "Activewear",
      "Sneakers",
      "Loafers_Oxford",
      "Boots_Sandals",
      "Caps_Hats",
      "Watches",
      "Bags_Backpacks",
      "Belts_Wallets",
      "Ties_Bow_Ties",
      "Sunglasses",
      "Other",
    ],
  },
  {
    name: "Babies_Kids",
    icon: "smile",
    subcategories: [
      "Baby_Clothing",
      "Kids_Clothing",
      "Baby_Shoes",
      "Kids_Shoes",
      "Baby_Toys",
      "Kids_Toys",
      "Educational_Toys",
      "Kids_Books",
      "Prams_Strollers",
      "Baby_Carriers",
      "Car_Seats",
      "Diapers_Nappies",
      "Baby_Food_Formula",
      "Feeding_Accessories",
      "Nursery_Furniture",
      "Baby_Monitors",
      "Bath_Safety",
      "Other",
    ],
  },
  {
    name: "Beauty_Personal_Care",
    icon: "heart",
    subcategories: [
      "Skincare",
      "Face_Serums_Treatments",
      "Moisturizers_Sunscreen",
      "Body_Lotions_Oils",
      "Hair_Care_Products",
      "Wigs_Hair_Extensions",
      "Hair_Tools_Styling",
      "Makeup_Foundation",
      "Makeup_Lips_Eyes",
      "Nail_Care",
      "Fragrances_Perfumes",
      "Deodorants",
      "Oral_Care",
      "Shaving_Grooming",
      "Bath_Body",
      "Hair_Removal",
      "Feminine_Care",
      "Beauty_Tools_Devices",
      "Other",
    ],
  },

  // ── AUTOMOTIVE ───────────────────────────────────────────────────────────
  {
    name: "Vehicles_Cars",
    icon: "truck",
    subcategories: [
      "Sedans",
      "SUVs",
      "Crossovers",
      "MPVs_Minivans",
      "Hatchbacks",
      "Station_Wagons",
      "Coupe_Convertibles",
      "Luxury_Cars",
      "Sports_Cars",
      "Electric_Hybrid_Cars",
      "Classic_Vintage_Cars",
      "Tokunbo_Foreign_Used",
      "Nigerian_Used",
      "Brand_New",
    ],
  },
  {
    name: "Commercial_Heavy_Duty",
    icon: "hard-drive",
    subcategories: [
      "Pickup_Trucks",
      "Box_Trucks",
      "Flatbed_Trucks",
      "Tippers_Dump_Trucks",
      "Reefer_Trucks",
      "Tankers",
      "Vans",
      "Mini_Buses",
      "Micro_Buses",
      "Coaches_Buses",
      "Trailers",
      "Tractors_Farm_Machinery",
      "Forklifts",
      "Construction_Vehicles",
      "Cranes_Heavy_Lifting",
      "Generators_Industrial",
    ],
  },
  {
    name: "Motorcycles_Powersports",
    icon: "zap",
    subcategories: [
      "Motorbikes",
      "Scooters_Mopeds",
      "Electric_Bikes",
      "Bicycles",
      "Tricycles_Keke_Napep",
      "ATVs_Quad_Bikes",
      "Dirt_Bikes",
      "Go_Karts_Buggies",
      "Boats_Jet_Skis",
      "Motorcycle_Accessories",
      "Helmets_Riding_Gear",
    ],
  },
  {
    name: "Auto_Parts_Care",
    icon: "settings",
    subcategories: [
      "Engine_Parts",
      "Transmission_Gearbox",
      "Suspension_Steering",
      "Braking_System",
      "Exhaust_System",
      "Tyres_Rims",
      "Batteries",
      "Electrical_Ignition",
      "Cooling_System",
      "Fuel_System",
      "Oils_Fluids_Filters",
      "Clutch_Drivetrain",
      "Body_Panels_Bumpers",
      "Lighting_Bulbs",
      "Car_Audio_GPS",
      "Interior_Accessories",
      "Exterior_Accessories",
      "Wiper_Blades",
      "Car_Care_Cleaning",
      "Other",
    ],
  },

  // ── HOME & LIVING ────────────────────────────────────────────────────────
  {
    name: "Home_Appliances",
    icon: "home",
    subcategories: [
      "Refrigerators",
      "Freezers",
      "Washing_Machines",
      "Dryers",
      "Dishwashers",
      "Air_Conditioners",
      "Fans_Air_Coolers",
      "Heaters",
      "Air_Purifiers",
      "Humidifiers_Dehumidifiers",
      "Microwaves",
      "Ovens_Cookers",
      "Air_Fryers",
      "Generators",
      "Inverters_UPS",
      "Solar_Panels_Systems",
      "Vacuum_Cleaners",
      "Steam_Cleaners",
      "Water_Heaters_Boilers",
      "Other",
    ],
  },
  {
    name: "Furniture",
    icon: "layers",
    subcategories: [
      "Sofas_Armchairs",
      "Beds_Mattresses",
      "Wardrobes_Closets",
      "Dressers_Vanities",
      "Dining_Sets",
      "Coffee_Side_Tables",
      "Console_Accent_Tables",
      "TV_Stands",
      "Bookshelves",
      "Office_Desks",
      "Office_Chairs",
      "Bar_Counter_Stools",
      "Outdoor_Furniture",
      "Ottomans_Poufs",
      "Kids_Furniture",
      "Other",
    ],
  },
  {
    name: "Home_Decor",
    icon: "sun",
    subcategories: [
      "Curtains_Blinds",
      "Rugs_Carpets",
      "Throw_Pillows_Blankets",
      "Wall_Art_Paintings",
      "Mirrors",
      "Indoor_Lighting",
      "Decorative_Vases",
      "Artificial_Plants_Flowers",
      "Picture_Frames",
      "Clocks",
      "Beddings_Duvet_Sets",
      "Candles_Diffusers",
      "Other",
    ],
  },
  {
    name: "Kitchen_Dining",
    icon: "coffee",
    subcategories: [
      "Pots_Pans_Cookware",
      "Knives_Cutlery",
      "Dinnerware_Plates",
      "Glassware_Cups",
      "Kitchen_Appliances",
      "Kitchen_Tools_Gadgets",
      "Food_Storage",
      "Water_Dispensers",
      "Trays_Serving",
      "Baking_Equipment",
      "Kitchen_Textiles",
      "Kitchen_Organisation",
      "Other",
    ],
  },

  // ── FOOD & GROCERIES ─────────────────────────────────────────────────────
  {
    name: "Fruits_Vegetables",
    icon: "target",
    subcategories: [
      "Fresh_Fruits",
      "Dried_Fruits",
      "Frozen_Fruits",
      "Fresh_Vegetables",
      "Frozen_Vegetables",
      "Fresh_Herbs_Seasonings",
      "Dried_Herbs_Spices",
      "Organic_Produce",
      "Exotic_Produce",
      "Other",
    ],
  },
  {
    name: "Meat_Fish_Poultry",
    icon: "heart",
    subcategories: [
      "Fresh_Chicken",
      "Turkey_Duck_Poultry",
      "Beef_Veal",
      "Lamb_Mutton",
      "Goat_Meat",
      "Pork",
      "Fresh_Fish",
      "Frozen_Fish",
      "Dried_Smoked_Fish",
      "Seafood_Shellfish",
      "Snail",
      "Game_Meat_Exotic",
      "Deli_Processed_Meat",
      "Frozen_Meals",
    ],
  },
  {
    name: "Rice_Beans_Grains",
    icon: "hash",
    subcategories: [
      "Local_Rice",
      "Imported_Foreign_Rice",
      "Brown_Wild_Rice",
      "Beans_Lentils",
      "Chickpeas_Peas",
      "Garri",
      "Cassava_Flour",
      "Semovita_Semolina",
      "Wheat_Flour",
      "Oats_Barley",
      "Millet_Sorghum",
      "Quinoa",
      "Corn_Maize",
      "Yam_Tubers",
      "Sweet_Potatoes",
      "Plantain_Cocoyam",
      "Other",
    ],
  },
  {
    name: "Beverages",
    icon: "coffee",
    subcategories: [
      "Soft_Drinks",
      "Energy_Sports_Drinks",
      "Fruit_Juices",
      "Smoothies_Blends",
      "Bottled_Water",
      "Tea",
      "Coffee",
      "Milk_Dairy_Drinks",
      "Malt_Drinks",
      "Wine",
      "Beer_Stout",
      "Spirits_Whiskey",
      "Zobo_Local_Drinks",
      "Fura_Kunu",
      "Protein_Shakes",
      "Other",
    ],
  },
  {
    name: "Packaged_Snacks_Condiments",
    icon: "package",
    subcategories: [
      "Snacks_Chips",
      "Biscuits_Cookies",
      "Chocolates_Candy",
      "Bread_Pastries",
      "Cereals_Granola",
      "Pasta_Noodles",
      "Canned_Foods",
      "Sauces_Ketchup",
      "Spices_Seasonings",
      "Cooking_Oils",
      "Honey_Jams_Spreads",
      "Sugar_Salt",
      "Tomato_Paste",
      "Dairy_Eggs",
      "Frozen_Snacks",
      "Other",
    ],
  },

  // ── HEALTH & MEDICAL ─────────────────────────────────────────────────────
  {
    name: "Health_Medical",
    icon: "activity",
    subcategories: [
      "Supplements_Vitamins",
      "Protein_Fitness_Nutrition",
      "Herbal_Natural_Remedies",
      "Blood_Pressure_Monitors",
      "Blood_Glucose_Monitors",
      "Thermometers",
      "Pulse_Oximeters",
      "Weighing_Scales",
      "Pregnancy_Fertility",
      "First_Aid_Kits",
      "Wound_Care",
      "Medical_Furniture_Beds",
      "Wheelchairs_Mobility_Aids",
      "Crutches_Walking_Aids",
      "Hearing_Aids",
      "Eye_Care_Glasses",
      "Dental_Products",
      "Face_Masks_PPE",
      "Sanitizers_Disinfectants",
      "Baby_Health_Products",
      "Other",
    ],
  },

  // ── SPECIALIZED ──────────────────────────────────────────────────────────
  {
    name: "Real_Estate",
    icon: "map",
    subcategories: [
      "For_Rent",
      "For_Sale",
      "For_Sharing",
      "Short_Let",
      "Serviced_Apartments",
      "Vacation_Rentals",
      "Lands_Plots",
      "Office_Space",
      "Co_Working_Spaces",
      "Meeting_Event_Spaces",
      "Shops_Retail_Space",
      "Warehouses",
      "Parking_Spaces",
    ],
  },
  {
    name: "Industrial_Business",
    icon: "briefcase",
    subcategories: [
      "Medical_Equipment",
      "Office_Equipment",
      "POS_Cash_Registers",
      "Restaurant_Kitchen_Equipment",
      "Bar_Equipment",
      "Bakery_Equipment",
      "Printing_Packaging",
      "Manufacturing_Equipment",
      "Agricultural_Equipment",
      "Construction_Equipment",
      "Mining_Equipment",
      "Retail_Shop_Fittings",
      "Safety_Fire_Equipment",
      "PPE_Protective_Gear",
      "Cleaning_Industrial",
      "Other",
    ],
  },
  {
    name: "Sports_Hobbies",
    icon: "award",
    subcategories: [
      "Gym_Fitness_Equipment",
      "Yoga_Pilates",
      "Cycling",
      "Swimming_Water_Sports",
      "Football_Team_Sports",
      "Racket_Sports",
      "Martial_Arts",
      "Outdoor_Camping",
      "Hunting_Fishing",
      "Board_Games_Puzzles",
      "Musical_Instruments",
      "Art_Craft_Supplies",
      "Photography_Videography",
      "Collectibles_Memorabilia",
      "Other",
    ],
  },
  {
    name: "Garden_Outdoor",
    icon: "sun",
    subcategories: [
      "Seeds_Seedlings",
      "Fertilizers_Soil",
      "Garden_Tools",
      "Lawn_Mowers",
      "Irrigation_Systems",
      "Planters_Pots",
      "Outdoor_Furniture",
      "BBQ_Grills",
      "Garden_Decor",
      "Pest_Control",
      "Composting",
      "Other",
    ],
  },
  {
    name: "Pets_Animals",
    icon: "heart",
    subcategories: [
      "Dog_Food_Treats",
      "Cat_Food_Treats",
      "Bird_Food",
      "Fish_Aquarium",
      "Pet_Accessories_Collars",
      "Pet_Toys",
      "Pet_Grooming",
      "Pet_Health_Medication",
      "Cages_Kennels",
      "Poultry_Livestock_Feed",
      "Farm_Animals",
      "Live_Birds_Pets",
      "Aquatic_Animals",
      "Other",
    ],
  },
  {
    name: "Other",
    icon: "package",
    subcategories: [
      "Books_Textbooks",
      "Comics_Graphic_Novels",
      "Manga_Anime",
      "Stationery_Office_Supplies",
      "Gift_Items_Hampers",
      "Religious_Items",
      "Traditional_Cultural_Items",
      "Event_Party_Supplies",
      "Seasonal_Holiday_Items",
      "DIY_Tools",
      "Sewing_Embroidery",
      "Knitting_Crochet",
      "Painting_Drawing",
      "Other",
    ],
  },
];

// === SERVICE PROVIDER CATEGORIES (SERVICES) ===
const SERVICE_PROVIDER_CATEGORIES = [
  {
    name: "Home_Repair_Maintenance",
    icon: "tool",
    subcategories: [
      "Plumbing",
      "Electrical_Works",
      "AC_Repair",
      "Carpentry",
      "Painting",
      "Tiling",
      "Roofing",
      "Solar_Setup",
      "Pest_Control",
      "Generator_Repair",
      "Home_Automation",
    ],
  },
  {
    name: "Cleaning_Services",
    icon: "wind",
    subcategories: [
      "House_Cleaning",
      "Office_Cleaning",
      "Fumigation",
      "Sofa_Carpet_Cleaning",
      "Laundry_Dry_Cleaning",
      "Pool_Cleaning",
      "Post_Construction_Cleaning",
    ],
  },
  {
    name: "Logistics_Transport",
    icon: "package",
    subcategories: [
      "Bike_Delivery",
      "Motor_Park_Agents",
      "Airport_Pickup_Agents",
      "Logistics_Company",
      "Moving_Relocation",
      "Truck_Haulage",
      "Private_Driver",
      "Airport_Pickup",
      "Area_Errands",
    ],
  },
  {
    name: "Real_Estate_Services",
    icon: "home",
    subcategories: [
      "Real_Estate_Agent",
      "Property_Sales_Leasing",
      "Facility_Management",
      "Land_Surveying",
      "Legal_Documentation",
      "Property_Valuation",
      "Short_Let_Apartments",
    ],
  },
  {
    name: "Tech_Gadgets_Repair",
    icon: "cpu",
    subcategories: [
      "Phone_Repair",
      "Laptop_Repair",
      "TV_Repair",
      "Printer_Repair",
      "DSTV_GOTV_Installation",
    ],
  },
  {
    name: "Automotive_Services",
    icon: "truck",
    subcategories: [
      "Mechanic",
      "Auto_Electrician",
      "Panel_Beating",
      "Car_Wash",
      "Towing_Services",
      "Car_Tracking_Installation",
      "Vehicle_Documentation",
    ],
  },
  {
    name: "Events_Entertainment",
    icon: "music",
    subcategories: [
      "Event_Planner",
      "DJ_MC",
      "Photographer",
      "Videographer",
      "Caterer",
      "Ushers",
      "Cake_Baker",
      "Makeup_Artist",
      "Security_Bouncers",
      "Live_Band",
      "Ushering_Services",
      "Event_Cleaning_Services",
    ],
  },
  {
    name: "Business_Professional",
    icon: "briefcase",
    subcategories: [
      "Graphic_Design",
      "Web_Development",
      "Digital_Marketing",
      "Legal_Services",
      "Accounting",
      "Architecture",
      "Interior_Design",
      "Visa_Travel_Consultant",
      "Business_Consulting",
      "Financial_Advising",
      "Project_Management",
      "Real_Estate_Agent",
    ],
  },
  {
    name: "Education_Lessons",
    icon: "book-open",
    subcategories: [
      "Home_Tutors",
      "Music_Lessons",
      "Driving_School",
      "Coding_Tech",
      "Language_Lessons",
      "Skill_Acquisition",
      "JAMB_WAEC_Lessons",
      "NECO_Lessons",
      "Post_UTME_Lessons",
      "Common_Entrance_Lessons",
      "Adult_Literacy_Lessons",
      "Special_Needs_Education",
      "Early_Childhood_Education",
    ],
  },
  {
    name: "Health_Wellness",
    icon: "activity",
    subcategories: [
      "Fitness_Trainer",
      "Massage_Therapist",
      "Home_Nurse",
      "Yoga_Instructor",
      "Nutritionist",
      "Physiotherapist",
      "Mental_Health_Counselor",
      "Occupational_Therapist",
      "Speech_Therapist",
    ],
  },
  {
    name: "Personal_Services",
    icon: "scissors",
    subcategories: [
      "Tailoring",
      "Fashion_Design",
      "Jewelry_Design",
      "Barbering",
      "Hair_Styling",
      "Manicure_Pedicure",
      "Nail_Technician",
      "Lashes_Brows",
      "Makeup_Artist",
      "Beauty_Salon",
      "Spa_Services",
    ],
  },
  {
    name: "Construction_Fabrication",
    icon: "box",
    subcategories: [
      "Welding_Iron_Work",
      "Wood_Work",
      "Metal_Fabrication",
      "Glass_Work",
      "Ceramic_Tiling",
      "Bricklaying",
      "Aluminum_Work",
      "POP_Ceiling",
      "Gate_Fence_Fabrication",
      "Plastic_Work",
    ],
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

const getSellerSubcategories = (categoryName) => {
  const cat = SELLERS_CATEGORIES.find((c) => c.name === categoryName);
  return cat ? [...cat.subcategories] : [];
};

const getServiceSubcategories = (categoryName) => {
  const cat = SERVICE_PROVIDER_CATEGORIES.find((c) => c.name === categoryName);
  return cat ? [...cat.subcategories] : [];
};

const CATEGORY_MAP = SELLERS_CATEGORIES.reduce((acc, cat) => {
  acc[cat.name] = [...cat.subcategories];
  return acc;
}, {});

const SERVICE_CATEGORY_MAP = SERVICE_PROVIDER_CATEGORIES.reduce((acc, cat) => {
  acc[cat.name] = [...cat.subcategories];
  return acc;
}, {});

module.exports = {
  SELLERS_CATEGORIES,
  SERVICE_PROVIDER_CATEGORIES,
  getSellerSubcategories,
  getServiceSubcategories,
  CATEGORY_MAP,
  SERVICE_CATEGORY_MAP,
};