// src/constants/Categories.js
// RULE: All `name` values use underscore_keys for i18n translation compatibility.
// This file is the SINGLE SOURCE OF TRUTH for category keys.
// Frontend Categories.ts must always mirror this file exactly.
// NEVER store display strings in the database — always store the raw underscore key.

// === SELLER CATEGORIES (PRODUCTS) ===
const SELLERS_CATEGORIES = [
  // ── ELECTRONICS ──────────────────────────────────────────────────────────
  {
    name: "Phones_Tablets",
    icon: "smartphone",
    subcategories: [
      "Smartphones",
      "Feature_Phones",
      "Tablets",
      "Phone_Accessories",
      "Chargers",
      "Accessories",
      "Power_Banks",
      "Phone_Cases",
      "Phone_Stands",
      "Screen_Protectors",
      "Earphones",
      "Smart_Speakers",
      "Smart_Watches",
      "Wearable_Technology",
    ],
  },
  {
    name: "Laptops_Computers",
    icon: "monitor",
    subcategories: [
      "Laptops",
      "Desktops",
      "All_in_One_Computers",
      "Gaming_Laptops",
      "Gaming_Desktops",
      "Gaming_PCs",
      "Monitors",
      "Chargers",
      "Printers",
      "Scanners",
      "Fax_Machines",
      "Accessories",
      "Computer_Accessories",
      "Storage_Devices",
      "Software",
    ],
  },
  {
    name: "TV_Audio_Gaming",
    icon: "tv",
    subcategories: [
      "Televisions",
      "Streaming_Devices",
      "Set_Top_BoX",
      "Blu_ray_Players",
      "Home_Theater",
      "Soundbars",
      "Speakers",
      "Accessories",
      "Gaming_Consoles",
      "VR_Headsets",
      "Video_Games",
      "Gaming_Accessories",
      "Projectors",
    ],
  },
  {
    name: "Cameras_Optics",
    icon: "camera",
    subcategories: [
      "Digital_Cameras",
      "Action_Cameras",
      "Camcorders",
      "Drones",
      "Accessories",
      "Gimbals",
      "Stabilizers",
      "Tripods",
      "Monopods",
      "Camera_Bags",
      "Camera_Straps",
      "Lenses",
      "Filters",
      "Lighting",
      "Backdrops",
      "Green_Screens",
      "Lighting_Stands",
      "Camera_Monitors",
      "Security_Cameras_CCTV",
      "Surveillance_Cameras",
      "Binoculars",
      "Monoculars",
      "Photography_Accessories",
      "Camera_Lenses",
      "Camera_Filters",
    ],
  },

  // ── FASHION & BEAUTY ─────────────────────────────────────────────────────
  {
    name: "Womens_Fashion",
    icon: "user",
    subcategories: [
      "Dresses",
      "Tops",
      "Blouses",
      "Sweaters",
      "Cardigans",
      "Coats_Jackets",
      "Hoodies_Sweatshirts",
      "Skirts",
      "Trousers_Jeans",
      "Native_Ankara",
      "Kimonos",
      "Jumpsuits",
      "Shorts",
      "Leggings",
      "Lingerie",
      "Sleepwear",
      "Activewear",
      "Footwear",
      "Accessories",
      "Shoes",
      "Bags",
      "Belts",
      "Jewelry",
      "Handbags",
      "Scarves",
    ],
  },
  {
    name: "Mens_Fashion",
    icon: "user",
    subcategories: [
      "Shirts",
      "T-Shirts",
      "Polo_Shirts",
      "Hoodies_Sweatshirts",
      "Sweatshirts",
      "Trousers",
      "Jeans",
      "Shorts",
      "Native_Wear",
      "Suits_Blazers",
      "Ties",
      "Bow_Ties",
      "Suspenders",
      "Underwear",
      "Sleepwear",
      "Activewear",
      "Footwear",
      "Accessories",
      "Shoes",
      "Caps",
      "Hats",
      "Watches",
      "Bags",
      "Belts_Wallets",
    ],
  },
  {
    name: "Babies_Kids",
    icon: "smile",
    subcategories: [
      "Baby_Clothing",
      "Baby_Shoes",
      "Baby_Toys",
      "Kids_Books",
      "Kids_Clothing",
      "Kids_Shoes",
      "Accessories",
      "Kids_Toys",
      "Prams_Strollers",
      "Diapers",
      "Baby_Food",
    ],
  },
  {
    name: "Beauty_Personal_Care",
    icon: "heart",
    subcategories: [
      "Skincare",
      "Face_Care",
      "Body_Care",
      "Hair_Care",
      "Wigs_Extensions",
      "Makeup",
      "Nail_Care",
      "Fragrances",
      "Accessories",
      "Perfumes",
      "Deodorants",
      "Oral_Care",
      "Hair_Removal",
      "Mens_Grooming",
      "Bath_Body",
    ],
  },

  // ── AUTOMOTIVE ───────────────────────────────────────────────────────────
  {
    name: "Vehicles_Cars",
    icon: "truck",
    subcategories: [
      "Sedans",
      "MPVs",
      "Crossover",
      "SUVs_Crossovers",
      "Station_Wagons",
      "Luxury_Cars",
      "Sports_Cars",
      "Coupes",
      "Hatchbacks",
      "Convertibles",
      "Electric_Hybrid_Cars",
      "Classic_Vintage_Cars",
      "Accessories",
    ],
  },
  {
    name: "Commercial_Heavy_Duty",
    icon: "hard-drive",
    subcategories: [
      "Pickup_Trucks",
      "Box_Trucks",
      "Flatbed_Trucks",
      "Reefer_Trucks",
      "Tippers_Dump_Trucks",
      "Tankers",
      "Vans_Buses",
      "Mini_Buses",
      "Micro_Buses",
      "Coaches",
      "Trailers",
      "Caravans",
      "Buses",
      "Tractors_Farm_Machinery",
      "Construction_Equipment",
      "Heavy_Machinery",
      "Forklifts",
      "Construction_Vehicles",
      "Heavy_Duty_Vehicles",
      "Trucks_Lorries",
      "Accessories",
    ],
  },
  {
    name: "Motorcycles_Powersports",
    icon: "zap",
    subcategories: [
      "Motorbikes",
      "Scooters",
      "Mopeds",
      "Electric_Bikes",
      "Bicycles",
      "ATVs_Quad_Bikes",
      "Dirt_Bikes",
      "Tricycles_Keke",
      "Go-Karts",
      "Buggies",
      "Boats_Jet_Skis",
      "Accessories",
    ],
  },
  {
    name: "Auto_Parts_Care",
    icon: "settings",
    subcategories: [
      "Engine_Parts",
      "Transmission_Parts",
      "Suspension_Parts",
      "Steering_Parts",
      "Exhaust_Parts",
      "Fuel_System_Parts",
      "Ignition_Parts",
      "Cooling_System_Parts",
      "Air_Conditioning_Parts",
      "Heating_System_Parts",
      "Braking_System_Parts",
      "Drivetrain_Parts",
      "Tyres_Rims",
      "Batteries",
      "Brake_Systems",
      "Lighting_Bulbs",
      "Car_Audio_GPS",
      "Brake_Pads",
      "Clutch_Parts",
      "Oils_Fluids",
      "Filters",
      "Wiper_Blade",
      "Exterior_Accessories",
      "Interior_Accessories",
      "Car_Care_Cleaning",
      "Accessories",
    ],
  },

  // ── HOME & LIVING ────────────────────────────────────────────────────────
  {
    name: "Home_Appliances",
    icon: "home",
    subcategories: [
      "Refrigerators",
      "Freezers",
      "Ovens",
      "Dishwashers",
      "Clothes_Dryers",
      "Washing_Machines",
      "Drying_Machines",
      "Air_Fryers",
      "Dehumidifiers",
      "Humidifiers",
      "Air_Purifiers",
      "Air_Conditioners",
      "Heaters",
      "Fans",
      "Microwaves",
      "Generators",
      "Inverters",
      "Power_Banks",
      "Solar_Panels",
      "Uninterruptible_Power_Supplies",
      "Vacuum_Cleaners",
      "Steam_Cleaners",
      "Accessories",
    ],
  },
  {
    name: "Furniture",
    icon: "layers",
    subcategories: [
      "Sofas_Chairs",
      "Coffee_Tables",
      "Side_Tables",
      "Console_Tables",
      "Electric_Tables",
      "Nest_Tables",
      "Accent_Tables",
      "End_Tables",
      "Beds_Mattresses",
      "Wardrobes",
      "Dressers",
      "Nightstands",
      "Vanities",
      "Ottomans",
      "Dining_Sets",
      "Bar_Stools",
      "Accessories",
      "Counter_Stools",
      "Dining_Chairs",
      "Office_Desks",
      "Office_Chairs",
      "Office_Tables",
      "Office_Furniture",
      "Outdoor_Furniture",
      "TV_Stands",
    ],
  },
  {
    name: "Home_Decor",
    icon: "sun",
    subcategories: [
      "Curtains_Blinds",
      "Rugs_Carpets",
      "Throw_Pillows",
      "Wall_Art",
      "Decorative_Accessories",
      "Lighting",
      "Beddings",
      "Mirrors",
      "Artificial_Flowers",
      "Accessories",
    ],
  },
  {
    name: "Kitchen_Dining",
    icon: "coffee",
    subcategories: [
      "Cookware",
      "Kitchen_Tools",
      "Kitchen_Appliances",
      "Kitchen_Furniture",
      "Kitchen_Textiles",
      "Kitchen_Storage",
      "Kitchen_Accessories",
      "Cutlery",
      "Dinnerware",
      "Glassware",
      "Storage_Organization",
      "Water_Dispensers",
      "Kitchen_Sinks",
      "Kitchen_Faucets",
      "Kitchen_Backsplashes",
      "Kitchen_Islands",
      "Kitchen_Countertops",
      "Accessories",
    ],
  },

  // ── FOOD & GROCERIES ─────────────────────────────────────────────────────
  {
    name: "Fruits_Vegetables",
    icon: "target",
    subcategories: [
      "Fresh_Fruits",
      "Dried_Fruits",
      "Frozen_Fruits",
      "Canned_Fruits",
      "Fresh_Vegetables",
      "Frozen_Vegetables",
      "Canned_Vegetables",
      "Fresh_Herbs",
      "Dried_Herbs",
      "Herbs_Sauces",
      "Herbs_Seasonings",
      "Organic_Produce",
      "Accessories",
    ],
  },
  {
    name: "Meat_Fish_Poultry",
    icon: "heart",
    subcategories: [
      "Chicken",
      "Turkey",
      "Duck",
      "Goose",
      "Quail",
      "Pigeon",
      "Guinea_Fowl",
      "Emu",
      "Ostrich",
      "Rabbit",
      "Bison",
      "Beef",
      "Veal",
      "Lamb",
      "Mutton",
      "Goat_Meat",
      "Fresh_Fish",
      "Frozen_Fish",
      "Dried_Fish",
      "Smoked_Fish",
      "Canned_Fish",
      "Seafood",
      "Frozen_Foods",
      "Deli_Meat",
      "Snail_Game_Meat",
    ],
  },
  {
    name: "Rice_Beans_Grains",
    icon: "hash",
    subcategories: [
      "Local_Rice",
      "Imported_Rice",
      "Foreign_Rice",
      "Exotic_Rice",
      "Wild_Rice",
      "Black_Rice",
      "Brown_Rice",
      "Red_Rice",
      "Purple_Rice",
      "Beans",
      "Lentils",
      "Chickpeas",
      "Peas",
      "Mung_Beans",
      "Garri",
      "Cassava",
      "Semovita",
      "Semolina",
      "Oats",
      "Barley",
      "Millet",
      "Quinoa",
      "Flour",
      "Yam_Tubers",
      "Sweet_Potatoes",
    ],
  },
  {
    name: "Beverages",
    icon: "coffee",
    subcategories: [
      "Soft_Drinks",
      "Energy_Drinks",
      "Sports_Drinks",
      "Protein_Shakes",
      "Meal_Replacements",
      "Juices",
      "Smoothies",
      "Bottled_Water",
      "Tea_Coffee",
      "Herbal_Tea",
      "Iced_Tea",
      "Cold_Brew_Coffee",
      "Nitro_Coffee",
      "Draft_Coffee",
      "Wine_Spirits",
      "Beer",
      "Cider",
      "Milk_Shakes",
      "Milk_Creams",
    ],
  },

  // ── SPECIALIZED ──────────────────────────────────────────────────────────
  {
    name: "Real_Estate",
    icon: "map",
    subcategories: [
      "For_Rent",
      "For_Sharing",
      "For_Sale",
      "Lands_Plots",
      "Short_Let",
      "Long_Let",
      "Vacation_Rentals",
      "Serviced_Apartments",
      "Office_Space",
      "Co_Working_Spaces",
      "Meeting_Rooms",
      "Event_Spaces",
      "Shops_Warehouses",
      "Parking_Spaces",
    ],
  },
  {
    name: "Industrial_Business",
    icon: "briefcase",
    subcategories: [
      "Medical_Equipment",
      "Office_Equipment",
      "Construction_Equipment",
      "Manufacturing_Equipment",
      "Mining_Equipment",
      "Printing_Packaging",
      "Agricultural_Equipment",
      "Restaurant_Supplies",
      "Bar_Equipment",
      "Cafe_Supplies",
      "Bakery_Equipment",
      "Retail_Shop_Fittings",
      "Safety_Equipment",
      "Personal_Protective_Equipment",
      "Fire_Safety_Equipment",
    ],
  },
  {
    name: "Sports_Hobbies",
    icon: "award",
    subcategories: [
      "Gym_Fitness",
      "Yoga",
      "Pilates",
      "Martial_Arts",
      "Dance",
      "Swimming",
      "Outdoor_Sports",
      "Team_Sports",
      "Individual_Sports",
      "Extreme_Sports",
      "Water_Sports",
      "Adventure_Travel",
      "Photography",
      "Videography",
      "Content_Creation",
      "Musical_Instruments",
      "Camping_Gear",
      "Board_Games",
    ],
  },
  {
    name: "Other",
    icon: "package",
    subcategories: [
      "Books",
      "Comics",
      "Graphic_Novels",
      "Manga",
      "Anime",
      "Stationery",
      "Pet_Supplies",
      "Accessories",
      "Collectibles",
      "Gift_Items",
      "Art_Supplies",
      "Craft_Supplies",
      "DIY_Tools",
      "Sewing_Embroidery",
      "Knitting_Crochet",
      "Painting_Drawing",
      "Art_Crafts",
    ],
  },
];

// === SERVICE PROVIDER CATEGORIES (SERVICES) ===
const SERVICE_PROVIDER_CATEGORIES = [
  {
    name: "Home_Repair_Maintenance",
    icon: "tool",
    subcategories: [
      "Plumbing",
      "Electrical_Works",
      "AC_Repair",
      "Carpentry",
      "Painting",
      "Tiling",
      "Roofing",
      "Generator_Repair",
      "Solar_Setup",
      "Pest_Control",
    ],
  },
  {
    name: "Cleaning_Services",
    icon: "wind",
    subcategories: [
      "House_Cleaning",
      "Office_Cleaning",
      "Fumigation",
      "Sofa_Carpet_Cleaning",
      "Laundry_Dry_Cleaning",
      "Pool_Cleaning",
    ],
  },
  {
    name: "Logistics_Transport",
    icon: "package",
    subcategories: [
      "Bike_Delivery",
      "Moving_Relocation",
      "Truck_Haulage",
      "Private_Driver",
      "Airport_Pickup",
    ],
  },
  {
    name: "Real_Estate_Services",
    icon: "home",
    subcategories: [
      "Property_Sales_Leasing",
      "Facility_Management",
      "Land_Surveying",
      "Legal_Documentation",
      "Property_Valuation",
      "Short_Let_Apartments",
    ],
  },
  {
    name: "Tech_Gadgets_Repair",
    icon: "cpu",
    subcategories: [
      "Phone_Repair",
      "Laptop_Repair",
      "TV_Repair",
      "Printer_Repair",
      "DSTV_GOTV_Installation",
    ],
  },
  {
    name: "Automotive_Services",
    icon: "truck",
    subcategories: [
      "Mechanic",
      "Auto_Electrician",
      "Panel_Beating",
      "Car_Wash",
      "Towing_Services",
      "Car_Tracking_Installation",
      "Vehicle_Documentation",
    ],
  },
  {
    name: "Events_Entertainment",
    icon: "music",
    subcategories: [
      "Event_Planner",
      "DJ_MC",
      "Photographer",
      "Videographer",
      "Caterer",
      "Cake_Baker",
      "Makeup_Artist",
      "Security_Bouncers",
      "Live_Band",
      "Ushering_Services",
    ],
  },
  {
    name: "Business_Professional",
    icon: "briefcase",
    subcategories: [
      "Graphic_Design",
      "Web_Development",
      "Digital_Marketing",
      "Legal_Services",
      "Accounting",
      "Real_Estate_Agent",
      "Architecture",
      "Interior_Design",
      "Visa_Travel_Consultant",
    ],
  },
  {
    name: "Education_Lessons",
    icon: "book-open",
    subcategories: [
      "Home_Tutors",
      "Music_Lessons",
      "Driving_School",
      "Coding_Tech",
      "Language_Lessons",
      "Skill_Acquisition",
      "JAMB_WAEC_Lessons",
    ],
  },
  {
    name: "Health_Wellness",
    icon: "activity",
    subcategories: [
      "Fitness_Trainer",
      "Massage_Therapist",
      "Home_Nurse",
      "Yoga_Instructor",
      "Nutritionist",
      "Physiotherapist",
    ],
  },
  {
    name: "Personal_Services",
    icon: "scissors",
    subcategories: [
      "Tailoring",
      "Barbering",
      "Hair_Styling",
      "Manicure_Pedicure",
      "Tattoo_Piercing",
      "Nail_Technician",
      "Lashes_Brows",
    ],
  },
  {
    name: "Construction_Fabrication",
    icon: "box",
    subcategories: [
      "Welding_Iron_Work",
      "Bricklaying",
      "Aluminum_Work",
      "POP_Ceiling",
      "Glass_Work",
      "Gate_Fence_Fabrication",
    ],
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

const getSellerSubcategories = (categoryName) => {
  const cat = SELLERS_CATEGORIES.find((c) => c.name === categoryName);
  return cat ? [...cat.subcategories] : [];
};

const getServiceSubcategories = (categoryName) => {
  const cat = SERVICE_PROVIDER_CATEGORIES.find((c) => c.name === categoryName);
  return cat ? [...cat.subcategories] : [];
};

module.exports = {
  SELLERS_CATEGORIES,
  SERVICE_PROVIDER_CATEGORIES,
  getSellerSubcategories,
  getServiceSubcategories,
};